# -*- coding: utf-8 -*-
"""FinalNetworkCreation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iMURyqMjGFMjkaoR3eZGUinmV2651B7G
"""

import csv
from tqdm import tqdm
import networkx as nx
import pandas as pd

# load data
df1 = pd.read_csv('/content/directors_movies.csv',header=0)
df2 = pd.read_csv('/content/final_credits.csv', header=0)

#match column names
df1=df1.rename(columns={"title_ids": "title_id"})

# create one df
merged_df = pd.merge(df2, df1, on='title_id',how='left')

# drop duplicate columns
merged_df=merged_df.drop(columns=["title"])

# drop directors
merged_df= merged_df.drop(merged_df[merged_df['Role']=="Directed by"].index)

#Creating weighted network
G = nx.DiGraph()

#add nodes
G.add_nodes_from(merged_df['Name'])
G.add_nodes_from(merged_df['director_name'])

for index, row in merged_df.iterrows():
  if G.has_edge(row[3], row[10]):
      # edge already exists, increase weight by one
      G[row[3]][row[10]]['weight'] += 1
  else:
      # add new edge with weight 1
      G.add_edge(row[3], row[10], weight = 1)

#save network
nx.write_gexf(G, "/content/director_crew_weighted.gexf")

#creating attribute network
G2 = nx.MultiDiGraph()
#add nodes
G2.add_nodes_from(merged_df['Name'])
G2.add_nodes_from(merged_df['director_name'])
edge_number=0
#create edges with attributes
for index, row in merged_df.iterrows():
  G2.add_edge(row[3], row[10], key=edge_number)
  attrs = {(row[3], row[10], edge_number): {"Year": row[8], "Role": row[2]}}
  nx.set_edge_attributes(G2, attrs)
  edge_number += 1

#save network
nx.write_gexf(G2, "/content/attributes.gexf")
